### ISSUE TITLE
Model selection for dynamical systems

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DataDrivenDiffEq.jl#23]
See https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.2017.0009

The hint is to adopt right away the Lorenz example for evaluation of DMD, EDMD and SInDy. This will allow of comparison in accuracy with the Matlab published papers and in speed with Julia.

A model selection function centered on AIC/BIC would then be an important extension to DataDrivenDiffEq.

**Comment by AlCap23** [comment]
Yeah, I was planning this ( liked the paper). I started working on this right on [this branch](https://github.com/JuliaDiffEq/DataDrivenDiffEq.jl/tree/aic_merge_basis). The difficulty is to calculate the number of free parameters from the resulting basis nicely, since we merge it right now. But feel free to use the branch!

**Comment by finmod** [comment]
The branch is working fine. The AIC function should be called AICC directly since the useful definition is the AIC Corrected throughout any model selection. Can you check that the formula in the function is correct: AIC = mlog(RSS/m) + 2k as in in the paper:

" RSS is a well-known objective function for least-squares fitting. In this case, AIC can be expressed as AIC=mln(RSS/m) + 2k [12]. Note that (2.1) penalizes, by increasing the AIC score, the models that have a large number of free parameters and which are unable to capture the characteristics of the observed data."

**Comment by AlCap23** [comment]
Closed via #41
